# Generated by Django 3.0.5 on 2020-08-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0002_auto_20200816_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_issues',
            name='assignee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo_issues',
            name='label',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repo_issues',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
