# Generated by Django 3.0.5 on 2020-08-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0003_auto_20200816_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_issues',
            old_name='label',
            new_name='labels',
        ),
        migrations.RenameField(
            model_name='repo_issues',
            old_name='status',
            new_name='state',
        ),
    ]
