# Generated by Django 3.0.5 on 2020-08-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0004_auto_20200816_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_issues',
            old_name='assignee',
            new_name='user',
        ),
    ]
