# Generated by Django 3.0.5 on 2020-08-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0005_auto_20200816_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo_issues',
            name='create_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
