# Generated by Django 3.0.5 on 2020-08-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0006_repo_issues_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_issues',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
